polls/urls.py
from django.conf.urls import patterns, url
from polls import views
# URL patterns specific to the POLLS app for Pollsite.
urlpatterns = patterns('',
	url(r'^(?P<user_id>\d+)/polls_page/$', views.polls_page, name='polls_page'),
	url(r'^(?P<user_id>\d+)/make_poll/$', views.make_poll, name='make_poll'),
	url(r'^(?P<user_id>\d+)/creating_poll/$', views.creating_poll, name='creating_poll'),
	url(r'^(?P<question_id>\d+)/(?P<user_id>\d+)/process_remove/$', views.process_remove, name='process_remove'),
	url(r'^(?P<question_id>\d+)/vote_poll/$', views.vote_poll, name='vote_poll'),
	url(r'^(?P<question_id>\d+)/processing_vote/$', views.processing_vote, name='processing_vote'),
)

pollsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

#The pollsite consists of two apps: a user authentication/authorization (USER) system and a voting system (POLLS).
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pollsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views
# URL patterns for the user authentication app.
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^processingsignup/$', views.processing_signup, name='processing_signup'),
	url(r'^processinglogin/$', views.processing_login, name='processing_login'),
	url(r'^welcome/(?P<user_id>\d+)/$', views.welcome, name='welcome'),
	url(r'^processinglogout/$', views.processing_logout, name='processing_logout'),
	url(r'^process_search/from/(?P<user_id>\d+)/$', views.process_search, name='process_search'),
)

polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# Models for the POLLS app: a Question with a corresponding set of Choices and a dictionary, or DictforQuestion, that has a set of Keyvalue objects.
# Each Keyvalue will have a KEY corresponding to the id of a user who has voted for the corresponding Question and a VALUE corresponding to the id
# of the Choice for which the KEY most recently voted.
class Question(models.Model):
	user = models.ForeignKey(User)
	text = models.CharField(max_length=200)
	date_published = models.DateTimeField()
	total_votes = models.IntegerField(default=0)
	def __str__(self):
		return self.text

class DictforQuestion(models.Model):
	question = models.OneToOneField(Question, primary_key=True)

class Keyvalue(models.Model):
	dictionary = models.ForeignKey(DictforQuestion)
	key = models.IntegerField()
	value = models.IntegerField()


class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from polls.models import Question, Choice, DictforQuestion, Keyvalue
from django.utils import timezone

#Views for the POLLS app for Pollsite.

def verify_authenticated(request, user_id):
	# Helper function for the following views. It makes sure that the current session's user matches the user to which the desired page belongs.
	# This way, users are unable to make/remove polls for other users. If the users don't match, the view redirects either to Pollsite's front INDEX
	# page (if the current session viewer is not signed up) or to the current session user's polls page with a warning.
	desired_user = get_object_or_404(User, pk=user_id)
	if request.user != desired_user:
		messages.add_message(request, messages.INFO, 'You are not authorized to view this page.')
		if not request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		return HttpResponseRedirect(reverse('polls:polls_page', args=(request.user.id,)))
	raise Exception()

def polls_page(request, user_id):
	# View for the polls page of the user with USER_ID(in the URL). It sets the proper permissions (explained in POLLS_PAGE template) for the
	# session user. It also orders the polls of the polls page owner by publication date.
	desired_user = get_object_or_404(User, pk=user_id)
	can_create, can_vote = True, True
	if request.user != desired_user:
		can_create = False
		if not request.user.is_authenticated():
			can_vote = False
	questions_list = desired_user.question_set.order_by('-date_published')
	return render(request, 'polls/polls_page.html', {'can_create': can_create, 'can_vote': can_vote, 'user': desired_user, 'questions_list': questions_list})

def make_poll(request, user_id):
	# View for the poll creation page of Pollsite.
	try:
		return verify_authenticated(request, user_id)
	except Exception:
		return render(request, 'polls/make_poll.html', {'user': request.user})

def creating_poll(request, user_id):
	# View that processes user input from the MAKE_POLL page. It first makes sure that all fields have been filled by the user and redirects
	# the user back to MAKE_POLL with an error message if this is not the case. Otherwise, it creates a Question object with a Choice set of
	# choices set by the user. It also creates a DictforQuestion object for that question (to eventually store a history of users who have
	# already voted for the question/poll). Finally, it redirects the user to his/her polls page, which should show the new poll.
	try:
		return verify_authenticated(request, user_id)
	except Exception:
		question_text = request.POST['question']
		if not question_text:
			error_message = 'You forgot to fill in some fields.'
			return render(request, 'polls/make_poll.html', {'user': request.user, 'error_message': error_message})
		num_choices = request.POST['selection']
		question = request.user.question_set.create(text=question_text, date_published=timezone.now(), total_votes=0)
		for i in range(int(num_choices)):
			text = request.POST['choice' + str(i+1)]
			if not text:
				question.delete()
				error_message = 'You forgot to fill in some fields.'
				return render(request, 'polls/make_poll.html', {'user': request.user, 'error_message': error_message})
			question.choice_set.create(choice_text=request.POST['choice' + str(i+1)], votes=0)
		dictionary = DictforQuestion(question=question)
		dictionary.save()
		return HttpResponseRedirect(reverse('polls:polls_page', args=(request.user.id,)))

def process_remove(request, question_id, user_id):
	# View that processes the user's request to remove a poll corresponding to QUESTION_ID and belonging to USER_ID. It deletes the poll 
	# or question and then returns to the current session user's polls page AFTER calling VERIFY_AUTHENTICATED.
	try:
		return verify_authenticated(request, user_id)
	except Exception:
		question = get_object_or_404(Question, pk=question_id)
		question.delete()
		return HttpResponseRedirect(reverse('polls:polls_page', args=(request.user.id,)))

def vote_poll(request, question_id):
	# View for the VOTE_POLL page (not for viewers who are not Pollsite users). The view finds the DictforQuestion (see POLLS app's models)
	# corresponding to the Question with QUESTION_ID(in the URL) and checks to see whether the current session user is in the keys of the
	# DictforQuestion's Keyvalue set(i.e. whether or not the user has voted on the Question before). If so, it sets SELECTED_CHOICE_ID to
	# the id of the user's most recent CHOICE in the poll. Otherwise, SELECTED_CHOICE_ID is set to None. Read more about SELECTED_CHOICE_ID's
	# purpose in the VOTE_POLL template.
	if not request.user.is_authenticated():
		messages.add_message(request, messages.INFO, 'You are not authorized to view this page.')
		return HttpResponseRedirect(reverse('users:index'))
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice_id = DictforQuestion.objects.get(question=question).keyvalue_set.get(key=request.user.id).value
	except Keyvalue.DoesNotExist:
		selected_choice_id = None
	return render(request, 'polls/vote_poll.html', {'question': question, 'selected_choice_id': selected_choice_id})

def processing_vote(request, question_id):
	# View that processes a user's vote input for a poll corresponding to QUESTION_ID(in the URL). This is not available for unregistered
	# users. The view first checks that a Choice of the poll was selected; it otherwise redirects the user to VOTE_POLL with an error message.
	# If the user has not previously voted in the poll, the view increments both the poll/question's total votes and the SELECTED_CHOICE's votes 
	# by 1 and stores the user with his/her inpt as a Keyvalue object in the poll's DictforQuestion. If the user HAS previously voted, the view
	# decrements the user's previous Choice by 1, increments his/her new Choice by 1, and updates the Keyvalue corresponding to the user with
	# the id of his/her new choice. Note that in this case, the poll/question's total votes stays the same. The view finally redirects the user
	# back to his/her own polls page with a success message verifying his/her submission.
	if not request.user.is_authenticated():
		messages.add_message(request, messages.INFO, 'You are not authorized to view this page.')
		return HttpResponseRedirect(reverse('users:index'))
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/vote_poll.html', {'question': question, 'selected_choice_id': None, 'error_message': "You did not select an available choice."})
	keyvalues = DictforQuestion.objects.get(question=question).keyvalue_set
	if request.user.id not in [keyvalue.key for keyvalue in keyvalues.all()]:
		question.total_votes += 1
		question.save()
		selected_choice.votes += 1
		selected_choice.save()
		keyvalues.create(key=request.user.id, value=selected_choice.id)
	else:
		target = keyvalues.get(key=request.user.id)
		previous_choice = question.choice_set.get(pk=target.value)
		if previous_choice != selected_choice:
			previous_choice.votes -= 1
			previous_choice.save()
			selected_choice.votes += 1
			selected_choice.save()
		target.value = selected_choice.id
		target.save()
	messages.add_message(request, messages.SUCCESS, 'Thanks! Your response has been recorded.')
	return HttpResponseRedirect(reverse('polls:polls_page', args=(request.user.id,)))

polls/templates/polls/make_poll.html
{% load staticfiles %}
<!-- Template for the MAKE_POLL page, where users can create new poll questions and choices for their own polls page. -->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'polls/darkly.css' %}"/>
	<script src="{% static 'polls/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'polls/bootstrap.min.js' %}"></script>
	<title>Create a Poll</title>
</head>
<body>
	<div class="jumbotron">
		<div class="container">
			<h1>Make your own poll!</h1>
		</div>
	</div>
	<!-- An error messages shows if the user does not fill in all required fields. -->
	{% if error_message %}
		<div class="container">
			<p class="bg bg-warning">{{error_message}}</p>
		</div>
	{% endif %}
	<!-- Form for poll creation. Includes fields for question text, number of poll choices, and text for each choice. Redirects on submission to CREATING_POLL view, which processes user input. -->
	<div class="container">
		<form action="{% url 'polls:creating_poll' user.id %}" method="post">
			{% csrf_token %}
			<!-- Question text field -->
			<div class="form-group">
				<label for="question">What's your poll asking?</label>
				<textarea class="form-control" rows="3" id="question" name="question" placeholder="Enter your poll question here"></textarea>
			</div>
			<!-- Selection feature to select number of choices (max 10). Powered by JQuery -->
			<label for="selection">How many choices for this poll?</label>
			<select class="form-control" id="selection" name="selection">
				<script>
					$(document).ready(function() {
						for (var i=1; i<=10; i++) {
							$('#selection').append('<option>'+String(i)+'</option>');
						}
						
					})
				</script>
			</select>
			</br>
			<!-- The following JS script makes the number of choice text fields dynamic and based on the user's selection above. -->
			<div id="choices">
			</div>
			<script>
				$(document).ready(function() {
					$('#selection').change(function() {
						$('#choices').empty();
						var $numChoices = Number($('select option:selected').text());
						for (var j=1; j<=$numChoices; j++) {
							$('#choices').append('<div class="form-group"><label for="choice' + String(j) + '">Choice ' + String(j) + '</label><input class="form-control" id="choice' + String(j) + '" name="choice' + String(j) + '" placeholder="Enter your choice text here"/>');
						}
					})
					$('#selection').trigger('change');
				})
			</script>
			<button type="submit" class="btn btn-success">Create Poll</button>
		</form>
	</div>
</body>
</html>

polls/templates/polls/polls_page.html
{% load staticfiles %}
<!-- Template for a user's POLLS_PAGE, which lists all of the polls that user has created. -->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'polls/darkly.css' %}"/>
	<script src="{% static 'polls/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'polls/bootstrap.min.js' %}"></script>
	<title>{{user.username}}'s Polls</title>
</head>
<body>
	<div class="jumbotron">
		<div class="container">
			<h1>{{user.username}}'s Polls</h1>
		</div>
		<!-- Only the user to which the polls page belongs can create and remove polls. And only users of Pollsite can log out and vote. The
		POLLS_PAGE view pointing to this template accounts for these permissions and sends them as context (can_create and can_vote). -->
		{% if can_vote %}
		<div class="container">
			<row>
				<!-- Button to create a poll. Leads to MAKE_POLL view. Only for the owner of the current polls page. -->
				<div class="col-xs-4">
					{% if can_create %}
						<a href="{% url 'polls:make_poll' user.id %}" role="button" class="btn btn-primary btn-lg btn-block">Create a new poll</a>
					{% endif %}
				</div>
				<!-- Button to remove a poll. Discussed more below -->
				<div class="col-xs-4">
					{% if can_create %}
						<button class="btn btn-primary btn-lg btn-block" id="remove">Remove a poll</button>
					{% endif %}
				</div>
				<!-- Logout button leading back to PROCESSING_LOGOUT in the USERS app. -->
				<div class="col-xs-4">
					<a href="{% url 'users:processing_logout' %}" role="button" class="btn btn-primary btn-lg btn-block">Logout</a>
				</div>
			</row>
		</div>
		{% endif %}
	</div>
	<!-- Users will see a success message if they successfully vote in a poll (which redirects them to their polls page). They will see warnings if they
	try to access pages of other users that they are not authorized to view. -->
	<div class="container">
		{% if messages %}
			{% for message in messages %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
					<p class="bg bg-success">{{message}}</p>
				{% else %}
					<p class="bg bg-warning">{{message}}</p>
				{% endif %}
			{% endfor %}
		{% endif %}
		<!-- The following is a search bar that lets users search for other Pollsite users by username or actual name. Input is processed by the
		PROCESS_SEARCH view. -->
		<row>
			<div class="col-xs-7">
			</div>
			<div class="col-xs-5">
				<form class="navbar-form navbar-left" role="search" action="{% url 'users:process_search' user.id %}" method="get">
					<div class="form-group">
						<input type="text" class="form-control" name="search" placeholder="Search full name/username"/>
					</div>
					<button type="submit" class="btn btn-primary">Search</button>
				</form>
			</div>
		</row>
		<!-- The table of polls that the owner of this poll page has made; for each poll, it shows the poll's question text, publication date,
		total number of votes, and a link for the current session's user to vote as well. -->
		<table class="table table-hover">
				<thead>
					<th>Question</th>
					<th>Date published</th>
					<th>Votes</th>
					<th>Vote now!</th>
					<th class="remove">Remove</th>
				</thead>
				<tbody>
					{% if not user.question_set.all %}
						<tr class="info">
							<td colspan="4" style="text-align:center">No polls yet!</td>
						</tr>
					{% else %}
						{% for poll in questions_list %}
							<tr class="info">
								<td>{{poll.text}}</td>
								<td>{{poll.date_published}}</td>
								<td>{{poll.total_votes}}</td>
								<td><a href={% if not can_vote %}"{% url 'users:signup' %}"{% else %}"{% url 'polls:vote_poll' poll.id %}"{% endif %}>Vote</a></td> <!-- If the current session's viewer has not signed up for Pollsite, he/she cannot vote and will be redirected to the signup page (the SIGNUP view in the USERS app. Otherwise, the user is redirected to a voting page for the desired poll (VOTE_POLL view). -->
								<td><a href="{% url 'polls:process_remove' poll.id user.id %}" class="remove">Remove</a></td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
		</table>
		<!-- JS for the remove feature (only available) if the current user is the owner of this polls page (can_create). Clicking on the Remove button will toggle the ability to remove polls (the table cells with class "remove" above). Clicking on one of these cells will redirect to a PROCESS_REMOVE view. -->
		<script>
			$(document).ready(function() {
				$('.remove').hide();
			})
		</script>
		{% if can_create %}
			<script>
				$(document).ready(function() {
					var $clicked = true;
					$('#remove').click(function() {
						if ($clicked) {
							$('.remove').show();
							$clicked = false;
						}
						else {
							$('.remove').hide();
							$clicked = true;
						}
					})
				})
			</script>
		{% endif %}
	</div>
</body>
</html>

polls/templates/polls/vote_poll.html
{% load staticfiles %}
<!-- Template for the VOTE_POLL page, which shows the target poll's question text, choices to pick from, and visual renderings of each choice's number of votes. -->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'polls/darkly.css' %}"/>
	<script src="{% static 'polls/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'polls/bootstrap.min.js' %}"></script>
	<title>Poll Voting</title>
</head>
<body>
	<div class="jumbotron">
		<div class="container">
			<h1>{{question.text}}</h1>
		</div>
	</div>
	<!-- A warning message appears if the user does not select a choice before submitting the vote form. -->
	{% if error_message %}
		<div class="container">
			<p class="bg bg-warning">{{error_message}}</p>
		</div>
	{% endif %}
	<div class="container">
		<!-- The vote form, which shows each of the poll's Choices as a radio button, along with a progress bar to display the popularity of each Choice. If the current session user has voted in this poll before, his/her previous Choice will be selected at the page's initial display. Otherwise, no Choice will be selected. The form redirects on submission to the PROCESSING_VOTE view.-->
		<form action="{% url 'polls:processing_vote' question.id %}" method="post" id="voteform">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
				<row>
					<div class="col-xs-12">
						<div class="radio">
							<label>
								<input class="choices" type="radio" name="choice" value="{{choice.id}}" {% if choice.id == selected_choice_id %}checked{% endif %}/> {{choice.choice_text}}
							</label>
						</div>
						<div class="progress">
							<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="{{choice.votes}}" aria-valuemin="0" aria-valuemax="{{question.total_votes}}" style="width: {% if question.total_votes == 0 %}0{% else %}{% widthratio choice.votes question.total_votes 100 %}{% endif %}%" id="{{choice.id}}">{{choice.votes}}</div>
						</div>
					</div>
				</row>
			{% endfor %}
			<button type="submit" class="btn btn-success">Vote</button>
		</form>
	</div>
	<!-- The following script powers the animation behind the Choice's progress bars, which are supposed to adjust based on the user's selection of the radio buttons. When selecting a new Choice, the progress bar of the previous Choice the user selected goes down by 1 vote (expressed in percents) and that of the new selected Choice goes up by 1 vote. Also note that if there is already a selected Choice at the page's initial display(meaning the user has voted in this poll before), the total number of Votes (totalVotes) used to calculate the width of progress bars remains the same as the poll/question's curent total number of votes, as opposed to being set to the current total number of votes + 1. In other words, a user CANNOT have more than one vote per poll. -->
	<script>
		$(document).ready(function() {
			var current = $('input[name=choice]:checked', '#voteform').val();
			if (current == null) {
				var totalVotes = Number($('.progress-bar').attr('aria-valuemax')) + 1;
			}
			else {
				var totalVotes = Number($('.progress-bar').attr('aria-valuemax'));
			}
			$('.choices').change(function() {
				var next = $('input[name=choice]:checked', '#voteform').val();
				var nextid = '#' + next;
				$(nextid).attr({
				 	'aria-valuenow': String(Number($(nextid).attr('aria-valuenow'))+1)
				});
				$(nextid).html(String(Number($(nextid).html())+1));
				if (current != null) {
					var former = '#' + current;
					$(former).attr({
						'aria-valuenow': String(Number($(former).attr('aria-valuenow'))-1)
					});
					$(former).html(String(Number($(former).html())-1));
				}
				{% for choice in question.choice_set.all %}
					var id = '#' + String({{choice.id}});
					$(id).css('width', String(100 * Number($(id).html())/totalVotes) + '%');
				{% endfor %}
				current = next;
			})
		})
	</script>
</body>
</html>