polls/urls.py
from django.conf.urls import patterns, url
from polls import views
# URL patterns specific to the POLLS app for Pollsite.
urlpatterns = patterns('',
	url(r'^(?P<user_id>\d+)/polls_page/$', views.polls_page, name='polls_page'),
	url(r'^(?P<user_id>\d+)/make_poll/$', views.make_poll, name='make_poll'),
	url(r'^(?P<user_id>\d+)/creating_poll/$', views.creating_poll, name='creating_poll'),
	url(r'^(?P<question_id>\d+)/(?P<user_id>\d+)/process_remove/$', views.process_remove, name='process_remove'),
	url(r'^(?P<question_id>\d+)/vote_poll/$', views.vote_poll, name='vote_poll'),
	url(r'^(?P<question_id>\d+)/processing_vote/$', views.processing_vote, name='processing_vote'),
)

pollsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

#The pollsite consists of two apps: a user authentication/authorization (USER) system and a voting system (POLLS).
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pollsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views
# URL patterns for the user authentication app.
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^processingsignup/$', views.processing_signup, name='processing_signup'),
	url(r'^processinglogin/$', views.processing_login, name='processing_login'),
	url(r'^welcome/(?P<user_id>\d+)/$', views.welcome, name='welcome'),
	url(r'^processinglogout/$', views.processing_logout, name='processing_logout'),
	url(r'^process_search/from/(?P<user_id>\d+)/$', views.process_search, name='process_search'),
)

users/models.py
from django.db import models


# Create your models here.

users/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages

#Views for the USERS app.

# Create your views here.
def index(request):
# View for your website's front page; if the user is already logged in, this will redirect to a WELCOME page for the user.
	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('users:welcome', args=(request.user.id,)))
	return render(request, 'users/index.html')

def signup(request):
# View for website's sign-up page.
	return render(request, 'users/signup.html', {'error_message': False})

def processing_signup(request):
# View for creating a new user who has just signed up; first checks that all fields are filled and that the desired username and email are free,
# then creates a new User object and logs it in. Finally redirects to the user's WELCOME page.
	firstname = request.POST['firstname']
	lastname = request.POST['lastname']
	emailaddress = request.POST['emailaddress']
	username = request.POST['username']
	password = request.POST['password']
	creds = []
	for cred in (firstname, lastname, emailaddress, username, password):
		if cred:
			creds.append(cred)
	if len(creds) != 5:
		error_message = 'You forgot to fill in some fields.'
	elif authenticate(username=username, password=password) is not None:
		error_message = 'This username is taken.'
	elif User.objects.filter(email=emailaddress):
		error_message = 'There is already an account associated with this email.'
	else:
		error_message = False
	if error_message:
		return render(request, 'users/signup.html', {'error_message': error_message})
	user = User.objects.create_user(username, emailaddress, password, first_name=firstname, last_name=lastname)
	user.save()
	user = authenticate(username=username, password=password)
	login(request, user)
	return HttpResponseRedirect(reverse('users:welcome', args=(user.id,)))

def processing_login(request):
# View that authenticates an attempted login. It returns the user back to the INDEX (front) page if credentials are invalid or inactive.
# Otherwise, the user is redirected to his/her WELCOME page.
	username = request.GET['username']
	password = request.GET['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			return HttpResponseRedirect(reverse('users:welcome', args=(user.id,)))
		else:
			messages.add_message(request, messages.INFO, 'This account is inactive.')
			return HttpResponseRedirect(reverse('users:index'))
	messages.add_message(request, messages.INFO, 'The username or password you entered is incorrect.')
	return HttpResponseRedirect(reverse('users:index'))

def welcome(request, user_id):
# View for a user's WELCOME page (the user's user_id is in the url pointing to this view). The view first checks that the user who is logged in
# matches the user for which the WELCOME page is intended (so users cannot simply type in the right URL).
	desired_user = get_object_or_404(User, pk=user_id)
	if request.user != desired_user:
		messages.add_message(request, messages.INFO, 'You are not authorized to view this page.')
		if not request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		return HttpResponseRedirect(reverse('polls:polls_page', args=(request.user.id,)))
	return render(request, 'users/welcome.html', {'user': desired_user})

def processing_logout(request):
# View to log out the current session's user and return to the website's front page.
	logout(request)
	return HttpResponseRedirect(reverse('users:index'))

def process_search(request, user_id):
	# View for processing a search query (search bar in a user's polls page). If the query matches an existing user's username,
	# the view redirects to THAT user's polls page. Otherwise, it redirects to the current session user's polls page with an error message.
	search_query = request.GET['search']
	try:
		user = User.objects.get(username=search_query)
	except User.DoesNotExist:
		messages.add_message(request, messages.INFO, "The user you're looking for could not be found.")
		return HttpResponseRedirect(reverse('polls:polls_page', args=(user_id,)))
	return HttpResponseRedirect(reverse('polls:polls_page', args=(user.id,)))

users/templates/users/index.html
{% load staticfiles %}
<!--The front page template for the target website using this USERS app (in this case Pollsite)-->
<html lang-"en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'users/darkly.css' %}"/>
	<script src="{% static 'users/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'users/bootstrap.min.js' %}"></script>
	<title>Welcome to Pollsite</title>
</head>
<body>
	<div class="jumbotron">
		<div class="container">
			<h1>Welcome to Pollsite!</h1>
			<p>Get started with the most convenient way to poll your friends by logging in or creating an account below.</p>
		</div>
	</div>

	<div class="container">
		<row>
			<!--Login button, which toggles the login form below-->
			<div class="col-xs-6">
				<button class="btn btn-primary btn-lg btn-block" id="login">Log in</button>
				<script>
					$(document).ready(function() {
						$('#loginform').hide();
						var $clicks = true;
						$('#login').click(function() {
							if ($clicks) {
								$('#loginform').show();
								$clicks = false;
							}
							else {
								$('#loginform').hide();
								$clicks = true;
							}
						})
					})
				</script>
			</div>
			<!--Sign up button leading to SIGNUP, the view for the sign up page-->
			<div class="col-xs-6">
				<a href="{% url 'users:signup' %}" role="button" class="btn btn-primary btn-lg btn-block">Sign up</a>
			</div>
		</row>
	</div>
	</br>
	<!--Login form, leads to PROCESSING_LOGIN, a view that authenticates the attempted login-->	
	<div class="container" id="loginform">
		<row>
			<form class="form-inline" action="{% url 'users:processing_login' %}" method="get">
				<div class="form-group">
					<label class="sr-only" for="userName">Username</label>
					<input type="text" class="form-control" id="userName" name="username" placeholder="Enter username"/>
				</div>
				<div class="form-group">
					<label class="sr-only" for="passWord">Password</label>
					<input type="password" class="form-control" id="passWord" name="password" placeholder="Enter password"/>
				</div>
				<button type="submit" class="btn btn-success">Log in</button>
			</form>
		</row>
	</div>
	<!-- A site visitor attempting to login/view pages requiring a site account without signing up will be redirected to this front page and see a warning message. -->
	{% if messages %}
		{% for message in messages %}
			<div class="container">
				<p class="bg bg-warning">{{message}}</p>
			</div>
		{% endfor %}
	{% endif %}
</body>
</html>

users/templates/users/signup.html
{% load staticfiles %}
<!-- Signup page template for new users of the target website. -->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'users/darkly.css' %}"/>
	<script src="{% static 'users/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'users/bootstrap.min.js' %}"></script>
	<title>Pollsite Signup</title>
</head>
<body>
	<div class="jumbotron">
		<div class="container">
			<h1>Sign up for Pollsite!</h1>
		</div>
	</div>
<!-- Error messages will appear if the user forgets to fill in fields of the sign-up form or if desired username/email is taken.-->
	{% if error_message %}
	<div class="container">
		<p class="bg bg-warning">{{error_message}}</p>
	</div>
	{% endif %}
	<!-- Form fields for first and last name, email, username, and password; the form redirects to the PROCESSING_SIGNUP view once submitted. -->
	<div class="container">
		<form action="{% url 'users:processing_signup' %}" method="post">
			{% csrf_token %}
			<div class="form-group">
				<label for="firstName">First Name</label>
				<input type="text" class="form-control" id="firstName" name="firstname" placeholder="Enter first name"/>
			</div>
			<div class="form-group">
				<label for="lastName">Last Name</label>
				<input type="text" class="form-control" id="lastName" name="lastname" placeholder="Enter last name"/>
			</div>
			<div class="form-group">
				<label for="emailAddress">Email Address</label>
				<input type="email" class="form-control" id="emailAddress" name="emailaddress" placeholder="Enter email address"/>
			</div>
			<div class="form-group">
				<label for="userName">Username</label>
				<input type="text" class="form-control" id="userName" name="username" placeholder="Enter username"/>
			</div>
			<div class="password">
				<label for="passWord">Password</label>
				<input type="password" class="form-control" id="passWord" name="password" placeholder="Enter password"/>
			</div>
			</br>
			<button type="submit" class="btn btn-success">Create Account</button>
		</form>
	</div>
</body>
</html>

users/templates/users/welcome.html
{% load staticfiles %}
<!-- Template for a logged-in user's WELCOME page, which is also, in Pollsite's case, the gateway to his/her polls. -->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'users/darkly.css' %}"/>
	<script src="{% static 'users/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'users/bootstrap.min.js' %}"></script>
	<title>{{user.username}} Gateway</title>
</head>
<body>
	<div class="jumbotron">
		<div class="container">
			<h1>Welcome, {{user.username}}!</h1>
			<!-- Buttons for polls, which leads to the POLLS app's POLLS_PAGE, and logging out, which leads to this app's PROCESSING_LOGOUT process. -->
			<row>
				<div class="col-xs-6">
					<a href="{% url 'polls:polls_page' user.id %}" role="button" class="btn btn-primary btn-lg btn-block">Head to your polls</a>
				</div>
				<div class="col-xs-6">
					<a href="{% url 'users:processing_logout' %}" role="button" class="btn btn-primary btn-lg btn-block">Logout</a>
				</div>
			</row>
		</div>
	</div>	
</body>
</html>